# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
cache: packages

r_check_args: '--as-cran'
#r_build_args: '--no-build-vignettes'
#r_check_args: '--as-cran --ignore-vignettes'

os:
  - linux
  - osx

brew_packages:
  - libgit2

r:
  - release
  - devel

r_binary_packages:
  - devtools
  - Rcpp
  - microbenchmark
  - covr

repos:
  CRAN: https://cloud.r-project.org

after_success:
    - Rscript -e 'covr::codecov()'
