# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
cache: packages
latex: false
fortran: false

#r_check_args: '--as-cran'
#r_build_args: '--no-build-vignettes'
r_check_args: '--as-cran --ignore-vignettes'

brew_packages:
  - libgit2

r:
  - release
  - devel

os:
  - linux
  - osx

r_packages:
  - covr
  - devtools
  - dplyr
  - ggplot2
  - microbenchmark
  - rmarkdown
  - testthat
  - jsonlite
  - purrr

branches:
  only:
  - master

matrix:
  fast_finish: true
  exclude:
    - os: osx
      r: devel

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"
  - TRAVIS_CXXFLAGS="-Wall -Wextra -pedantic -Werror"
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true

repos:
  CRAN: https://cloud.r-project.org

after_success:
    - Rscript -e 'covr::codecov()'

notifications:
  email:
    recipients:
      - brucezhaor@163.com
      - zhaowei@chinaubi.com
    on_success: change
    on_failure: always
