# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
cache: packages

#r_check_args: '--as-cran'
#r_build_args: '--no-build-vignettes'
r_check_args: '--as-cran --ignore-vignettes'

brew_packages:
  - libgit2

r:
  - release
  - devel

os:
  - linux
  - osx

r_packages:
  - covr
  - devtools
  - dplyr
  - ggplot2
  - microbenchmark
  - rmarkdown
  - testthat

branches:
  only:
  - master

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
      r: devel

repos:
  CRAN: https://cloud.r-project.org

after_success:
    - Rscript -e 'covr::codecov()'

notifications:
  email:
    recipients:
      - brucezhaor@163.com
      - zhaowei@chinaubi.com
    on_success: change
    on_failure: always

