---
title: "A Demo of Risk Factors To Score"
author: "Wei Zhao"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{risk factors to score demo}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
options(tibble.print_min = 4L, tibble.print_max = 4L)
```

**For the best result printing, let't `library(tibble)` or `dplyr`.**    


```{r load-pkg}
library(pjutils)
library(tibble)
# library(dplyr)
```

Here is a demo of using the functions:     

The binary search have two version:    

- r version, start from 1, which if faster when the `length(y)` is large than 1e5.
- cpp version start form 0, which if faster when `length(y)` is small than 1e5.

```{r demo-bs}
# binary search
binary_search_r(1.3, 1:10)
binary_search_cpp(1.3, 1:10)

binary_search_r(9.9, 1:10)
binary_search_cpp(9.9, 1:10)

binary_search_r(0.9, 1:10)
binary_search_cpp(0.9, 1:10)

binary_search_r(10.9, 1:10)
binary_search_cpp(10.9, 1:10)

```

The `get_score` apply to a sigle value while `get_socre_vec` can apply to a
vector of vaues: 

```{r demo-getScore}
# get score
values <- c(55, 60, 65, 70, 75, 80, 85, 90, 95, 100)
scores <- c(1.0000, 0.9747, 0.8967, 0.8303, 0.7730, 0.7232, 0.6793, 0.6405, 0.6059, 0.5748)
get_score(55, values, scores)
get_score(57.5, values, scores)
get_score(97.5, values, scores)
get_score(77, values, scores)
get_score(100, values, scores)
get_score(101, values, scores)

get_score_vec(c(55, 57.5, 97.5, 77, 100, 101), values, scores)

```


-------------------------------------------------------------------------------
