# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Binary search cpp version
#'
#' @param x A double to be find
#' @param y A double vector
#' @return A integer of position
#' @author Zhaowei
#' @export
binary_search_cpp <- function(x, y) {
    .Call(`_pjutils_binary_search_cpp`, x, y)
}

